apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payments-dev
  namespace: argocd
spec:
  project: payments
  source:
    repoURL: git@github.com:mehtachirag186/case-study-1-infra.git
    targetRevision: main
    path: apps/payments/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: team-payments-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=True
